name: HomingBow
version: 1.0.1-mobonly-fixed
main: me.galaxy.homingbow.HomingBowPlugin
api-version: "1.21"
author: Galaxy
description: Mob-only homing arrows for a special ItemsAdder bow (CMD match) with player-avoidance
commands:
  homingbowreload:
    description: Reload HomingBow config
    permission: homingbow.admin
permissions:
  homingbow.admin:
    default: op
commands:
  lunarfix:
    description: Lunar Bow lore + infinity + unbreakable fix
    usage: /lunarfix
